import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useState, useEffect, useContext } from "react"
import { useToken } from '../hooks/useToken'



export default function Home() {

  const [theMenu, setTheMenu] = useState(null)

  const token = useToken()
 

 

  function menu() {
    if (token) {

      const requestOptions = {
        method: 'GET',
        redirect: 'follow',
        headers: {
          "Authorization": `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
      };

      fetch("https://dev-mrp.insby.tech/api/session/restaurant/menu", requestOptions)
        .then(response => response.json())
        .then(result => {
          console.log(result.data);
          setTheMenu(result.data)
        })
        .catch(error => console.log('error', error));
    }
  }

  useEffect(() => {

    if (token) {
      menu()
    } else {
      return <h1>Loading...</h1>
    }
  },[token])
 
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {theMenu?.map(item => (
          <div key={item.category_id}>
            <h3 className={styles.category_name}>{item.category_name}</h3>
            <ul>
              {item.items.map(i => (
                <li className={styles.list} key={i.rmci_id}>
                  <Image className={styles.food_image} width={150} height={150} src={`https://files.insby.tech/tap-dev-4/${i.product_variant_image_url}`} alt={i.product_variant_name} />
                  <p className={styles.food_name}>{i.product_variant_name}</p>
                  <p className={styles.food_price} >{i.product_variant_price.display_price }</p>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </div>
  )
}
